### ISSUE TITLE
Simplify development by migrating to using Ruff in place of other code quality checks

### ISSUE THREAD

**Issue by vincentdavis** [koenvervloesem/bluetooth-numbers#44]
To check, catch, and fix more code quality issues maybe it would be possible to make more use of Ruff in replacing other checks and making more use of fix.

- Replace interrogate with  pydocstyle: https://docs.astral.sh/ruff/rules/#pydocstyle-d
- I see a `.isort.cfg` file, I am not sure what is using this as I dont see isort being used or installed. 
Use Ruff's isort option with auto fix https://docs.astral.sh/ruff/rules/#isort-i I see a 
- Others?

**Comment by koenvervloesem** [comment]
- The `.isort.cfg` file is a leftover, that should've been deleted after the switch from Flake8, isort and so on to Ruff.
- Interrogate can probably be removed as well, as Ruff has pydocstyle indeed.
- I made only a subset of the rules automatically fixable (https://github.com/koenvervloesem/bluetooth-numbers/blob/main/pyproject.toml#L18). I don't remember whether some of the others were resulting in problems, but feel free to suggest specific rules that are safe to automatically apply.
