### ISSUE TITLE
PyPI latest version doesn't have latest data from main

### ISSUE THREAD

**Issue by ukBaz** [koenvervloesem/bluetooth-numbers#51]
The latest version currently on PyPI is v1.1.1 which is behind what is on main.

For example I was trying to lookup the company id of `0x0cc8` which is successful on `main`, but not if I use the version installed from PyPI.

Are there plans to update the PyPI version?

**Comment by koenvervloesem** [comment]
Yes, I'm currently planning to change the source of the numbers in this package (see https://github.com/koenvervloesem/bluetooth-numbers/pull/49#issuecomment-2289642471), but I'll publish an update with the current numbers.

**Comment by ukBaz** [comment]
Thanks

**Comment by koenvervloesem** [comment]
New release is on PyPI: https://github.com/koenvervloesem/bluetooth-numbers/releases/tag/v1.1.2

The plan is to automate this package's updates on PyPI using the YAML files from the [Bluetooth SIG public repository](https://bitbucket.org/bluetooth-SIG/public/src/main/).
